### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JohnDMcMaster** [jodonnell/Minesweeper-#1]
What license is your project under?  I need something like Django minesweeper but I don't do a lot of web stuff so looking for a good starting place.  For me to consider using your project it would need to be either public domain or BSD (no GPL).  Thanks!

**Comment by jodonnell** [comment]
added a license for you.  this is a project i made for a job interview 5 years back.  as i recall i had at least one problem with it, you can select a mine on your first click, where in the original minesweeper you could never select a mine on your first click.  feel free to use it.

**Comment by JohnDMcMaster** [comment]
Thanks!
